---
title: "rna_seq_analysis"
output: html_notebook
---

Data Preparation
================
```{r "data prep", message = FALSE}
library(tidyverse)

mouse = read_tsv(file = "rnaseq_counts.txt", col_types = cols(Chromosome = col_character()))

mouse %>% 
  select(Probe, Chromosome:Distance) -> mouse.annot

mouse %>% 
  select(Probe, Ish_1:T47D_1) %>% 
  pivot_longer(cols = Ish_1:T47D_1, names_to = c("Condition", "Replicate"), names_sep = "_",
               values_to = "Counts") %>% 
  mutate(Sample = paste(Condition, Replicate, sep = "_")) %>% 
  relocate(Sample, .after = Probe) %>% 
  group_by(Probe) %>% 
  filter(sum(Counts) > 0) %>% 
  ungroup() -> mouse.counts
```


Data Normalization and Summarization
====================================
```{r "violin plots"}
mouse.counts %>% 
  mutate(Counts_Norm = (log2(1 + Counts))/1000000) -> mouse.counts

mouse.counts %>% 
  ggplot(aes(x = Sample, y = Counts_Norm, color = Condition)) + geom_violin()
```
```{r "data restructure"}
mouse.counts %>% 
  group_by(Probe, Condition) %>% 
  summarize(meanLog2rpm = mean(Counts_Norm)) %>% 
  pivot_wider(names_from = Condition, values_from = meanLog2rpm) -> summarized.counts
```


Plotting and Analysis
=====================
